<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    private const CURRENCIES = [
        ['iso_code' => 'AED', 'name' => 'UAE Dirham', 'symbol' => 'د.م.'],
        ['iso_code' => 'AFN', 'name' => 'Afghani', 'symbol' => '؋'],
        ['iso_code' => 'ALL', 'name' => 'Lek', 'symbol' => 'Lek'],
        ['iso_code' => 'AMD', 'name' => 'Armenian Dram', 'symbol' => 'Դ'],
        ['iso_code' => 'ANG', 'name' => 'Netherlands Antillean guilder', 'symbol' => 'ƒ'],
        ['iso_code' => 'AOA', 'name' => 'Kwanza', 'symbol' => 'is'],
        ['iso_code' => 'ARS', 'name' => 'Argentine Peso', 'symbol' => '$'],
        ['iso_code' => 'AUD', 'name' => 'Australian Dollar', 'symbol' => '$'],
        ['iso_code' => 'AWG', 'name' => 'Aruban Florin', 'symbol' => 'ƒ'],
        ['iso_code' => 'AZN', 'name' => 'Manat', 'symbol' => '₼'],
        ['iso_code' => 'BAM', 'name' => 'Convertible Mark', 'symbol' => 'КМ'],
        ['iso_code' => 'BBD', 'name' => 'Barbados Dollar', 'symbol' => '$'],
        ['iso_code' => 'BDT', 'name' => 'Taka', 'symbol' => '৳'],
        ['iso_code' => 'BES', 'name' => 'US Dollar', 'symbol' => '$'],
        ['iso_code' => 'BGN', 'name' => 'Bulgarian Lev', 'symbol' => 'лв'],
        ['iso_code' => 'BHD', 'name' => 'Bahraini Dinar', 'symbol' => 'ب.د'],
        ['iso_code' => 'BIF', 'name' => 'Burundi Franc', 'symbol' => '₣'],
        ['iso_code' => 'BMD', 'name' => 'Bermudian Dollar', 'symbol' => '$'],
        ['iso_code' => 'BND', 'name' => 'Brunei Dollar', 'symbol' => '$'],
        ['iso_code' => 'BOB', 'name' => 'Boliviano', 'symbol' => 'Bs.'],
        ['iso_code' => 'BOV', 'name' => 'Mvdol', 'symbol' => 'Mvdol'],
        ['iso_code' => 'BRL', 'name' => 'Brazilian Real', 'symbol' => 'R$'],
        ['iso_code' => 'BSD', 'name' => 'Bahamian Dollar', 'symbol' => '$'],
        ['iso_code' => 'BTN', 'name' => 'Ngultrum', 'symbol' => 'Nu'],
        ['iso_code' => 'BWP', 'name' => 'Pula', 'symbol' => 'P'],
        ['iso_code' => 'BYN', 'name' => 'Belarussian Ruble', 'symbol' => 'p.'],
        ['iso_code' => 'BZD', 'name' => 'Belize Dollar', 'symbol' => '$'],
        ['iso_code' => 'CAD', 'name' => 'Canadian Dollar', 'symbol' => '$'],
        ['iso_code' => 'CDF', 'name' => 'Congolese Franc', 'symbol' => '₣'],
        ['iso_code' => 'CHF', 'name' => 'Swiss Franc', 'symbol' => 'CHF'],
        ['iso_code' => 'CLP', 'name' => 'Chilean Peso', 'symbol' => '$'],
        ['iso_code' => 'CNY', 'name' => 'Yuan Renminbi', 'symbol' => '¥'],
        ['iso_code' => 'COP', 'name' => 'Colombian Peso', 'symbol' => '$'],
        ['iso_code' => 'CRC', 'name' => 'Costa Rican Colon', 'symbol' => '₡'],
        ['iso_code' => 'CUP', 'name' => 'Cuban Peso', 'symbol' => '₱'],
        ['iso_code' => 'CVE', 'name' => 'Cape Verde Escudo', 'symbol' => '$'],
        ['iso_code' => 'CZK', 'name' => 'Czech Koruna', 'symbol' => 'Kč'],
        ['iso_code' => 'DJF', 'name' => 'Djibouti Franc', 'symbol' => '₣'],
        ['iso_code' => 'DKK', 'name' => 'Danish Krone', 'symbol' => 'kr.'],
        ['iso_code' => 'DOP', 'name' => 'Dominican Peso', 'symbol' => '$'],
        ['iso_code' => 'DZD', 'name' => 'Algerian Dinar', 'symbol' => 'د.ج'],
        ['iso_code' => 'EGP', 'name' => 'Egyptian Pound', 'symbol' => '£'],
        ['iso_code' => 'ERN', 'name' => 'Nakfa', 'symbol' => 'Nfk'],
        ['iso_code' => 'ETB', 'name' => 'Ethiopian Birr', 'symbol' => 'Br'],
        ['iso_code' => 'EUR', 'name' => 'Euro', 'symbol' => '€'],
        ['iso_code' => 'FJD', 'name' => 'Fiji Dollar', 'symbol' => '$'],
        ['iso_code' => 'FKP', 'name' => 'Falkland Islands Pound', 'symbol' => '£'],
        ['iso_code' => 'GBP', 'name' => 'Pound Sterling', 'symbol' => '£'],
        ['iso_code' => 'GEL', 'name' => 'Lari', 'symbol' => 'ლ'],
        ['iso_code' => 'GHS', 'name' => 'Ghana Cedi', 'symbol' => '₵'],
        ['iso_code' => 'GIP', 'name' => 'Gibraltar Pound', 'symbol' => '£'],
        ['iso_code' => 'GMD', 'name' => 'Dalasi', 'symbol' => 'D'],
        ['iso_code' => 'GNF', 'name' => 'Guinea Franc', 'symbol' => '₣'],
        ['iso_code' => 'GTQ', 'name' => 'Quetzal', 'symbol' => 'Q'],
        ['iso_code' => 'GYD', 'name' => 'Guyana Dollar', 'symbol' => '$'],
        ['iso_code' => 'HKD', 'name' => 'Hong Kong Dollar', 'symbol' => '$'],
        ['iso_code' => 'HNL', 'name' => 'Lempira', 'symbol' => 'L'],
        ['iso_code' => 'HRK', 'name' => 'Kuna', 'symbol' => 'Kn'],
        ['iso_code' => 'HTG', 'name' => 'Gourde', 'symbol' => 'G'],
        ['iso_code' => 'HUF', 'name' => 'Forint', 'symbol' => 'Ft'],
        ['iso_code' => 'IDR', 'name' => 'Rupiah', 'symbol' => 'Rp'],
        ['iso_code' => 'ILS', 'name' => 'New Israeli Sheqel', 'symbol' => '₪'],
        ['iso_code' => 'INR', 'name' => 'Indian Rupee', 'symbol' => '₨'],
        ['iso_code' => 'IQD', 'name' => 'Iraqi Dinar', 'symbol' => 'ع.د'],
        ['iso_code' => 'IRR', 'name' => 'Iranian Rial', 'symbol' => '﷼'],
        ['iso_code' => 'ISK', 'name' => 'Iceland Krona', 'symbol' => 'Kr'],
        ['iso_code' => 'JMD', 'name' => 'Jamaican Dollar', 'symbol' => '$'],
        ['iso_code' => 'JOD', 'name' => 'Jordanian Dinar', 'symbol' => 'د.ا'],
        ['iso_code' => 'JPY', 'name' => 'Yen', 'symbol' => '¥'],
        ['iso_code' => 'KES', 'name' => 'Kenyan Shilling', 'symbol' => 'Sh'],
        ['iso_code' => 'KGS', 'name' => 'Som', 'symbol' => 'лв'],
        ['iso_code' => 'KHR', 'name' => 'Riel', 'symbol' => '៛'],
        ['iso_code' => 'KMF', 'name' => 'Comoro Franc', 'symbol' => 'FC'],
        ['iso_code' => 'KPW', 'name' => 'North Korean Won', 'symbol' => '₩'],
        ['iso_code' => 'KRW', 'name' => 'Won', 'symbol' => '₩'],
        ['iso_code' => 'KWD', 'name' => 'Kuwaiti Dinar', 'symbol' => 'د.ك'],
        ['iso_code' => 'KYD', 'name' => 'Cayman Islands Dollar', 'symbol' => '$'],
        ['iso_code' => 'KZT', 'name' => 'Tenge', 'symbol' => '〒'],
        ['iso_code' => 'LAK', 'name' => 'Kip', 'symbol' => '₭'],
        ['iso_code' => 'LBP', 'name' => 'Lebanese Pound', 'symbol' => 'ل.ل'],
        ['iso_code' => 'LKR', 'name' => 'Sri Lanka Rupee', 'symbol' => 'Rs'],
        ['iso_code' => 'LRD', 'name' => 'Liberian Dollar', 'symbol' => '$'],
        ['iso_code' => 'LSL', 'name' => 'Loti', 'symbol' => 'L'],
        ['iso_code' => 'LYD', 'name' => 'Libyan Dinar', 'symbol' => 'ل.د'],
        ['iso_code' => 'MAD', 'name' => 'Moroccan Dirham', 'symbol' => 'د.م.'],
        ['iso_code' => 'MDL', 'name' => 'Moldovan Leu', 'symbol' => 'L'],
        ['iso_code' => 'MGA', 'name' => 'Malagasy Ariary', 'symbol' => 'MK'],
        ['iso_code' => 'MKD', 'name' => 'Denar', 'symbol' => 'ден'],
        ['iso_code' => 'MMK', 'name' => 'Kyat', 'symbol' => 'K'],
        ['iso_code' => 'MNT', 'name' => 'Tugrik', 'symbol' => '₮'],
        ['iso_code' => 'MOP', 'name' => 'Pataca', 'symbol' => 'P'],
        ['iso_code' => 'MRU', 'name' => 'Ouguiya', 'symbol' => 'UM'],
        ['iso_code' => 'MUR', 'name' => 'Mauritius Rupee', 'symbol' => '₨'],
        ['iso_code' => 'MVR', 'name' => 'Rufiyaa', 'symbol' => 'ރ'],
        ['iso_code' => 'MWK', 'name' => 'Kwacha', 'symbol' => 'MK'],
        ['iso_code' => 'MXN', 'name' => 'Mexican Peso', 'symbol' => '$'],
        ['iso_code' => 'MXV', 'name' => 'Mexican Unidad de Inversion (UDI)', 'symbol' => '-'],
        ['iso_code' => 'MYR', 'name' => 'Malaysian Ringgit', 'symbol' => 'RM'],
        ['iso_code' => 'MZN', 'name' => 'Mozambique Metical', 'symbol' => 'MTn'],
        ['iso_code' => 'NAD', 'name' => 'Namibia Dollar', 'symbol' => '$'],
        ['iso_code' => 'NGN', 'name' => 'Naira', 'symbol' => '₦'],
        ['iso_code' => 'NIO', 'name' => 'Cordoba Oro', 'symbol' => 'C$'],
        ['iso_code' => 'NOK', 'name' => 'Norwegian Krone', 'symbol' => 'kr'],
        ['iso_code' => 'NPR', 'name' => 'Nepalese Rupee', 'symbol' => '₨'],
        ['iso_code' => 'NZD', 'name' => 'New Zealand Dollar', 'symbol' => '$'],
        ['iso_code' => 'OMR', 'name' => 'Rial Omani', 'symbol' => '﷼'],
        ['iso_code' => 'PAB', 'name' => 'Balboa', 'symbol' => 'B/.'],
        ['iso_code' => 'PEN', 'name' => 'Nuevo Sol', 'symbol' => 'S/.'],
        ['iso_code' => 'PGK', 'name' => 'Kina', 'symbol' => 'K'],
        ['iso_code' => 'PHP', 'name' => 'Philippine Peso', 'symbol' => '₱'],
        ['iso_code' => 'PKR', 'name' => 'Pakistan Rupee', 'symbol' => '₨'],
        ['iso_code' => 'PLN', 'name' => 'Zloty', 'symbol' => 'zł'],
        ['iso_code' => 'PYG', 'name' => 'Guarani', 'symbol' => '₲'],
        ['iso_code' => 'QAR', 'name' => 'Qatari Rial', 'symbol' => 'ر.ق'],
        ['iso_code' => 'RON', 'name' => 'Romanian Leu', 'symbol' => 'L'],
        ['iso_code' => 'RSD', 'name' => 'Serbian Dinar', 'symbol' => 'din'],
        ['iso_code' => 'RUB', 'name' => 'Russian Ruble', 'symbol' => '₽'],
        ['iso_code' => 'RWF', 'name' => 'Rwanda Franc', 'symbol' => '₣'],
        ['iso_code' => 'SAR', 'name' => 'Saudi Riyal', 'symbol' => 'ر.س'],
        ['iso_code' => 'SBD', 'name' => 'Solomon Islands Dollar', 'symbol' => '$'],
        ['iso_code' => 'SCR', 'name' => 'Seychelles Rupee', 'symbol' => 'Rs'],
        ['iso_code' => 'SDG', 'name' => 'Sudanese Pound', 'symbol' => '£'],
        ['iso_code' => 'SEK', 'name' => 'Swedish Krona', 'symbol' => 'kr'],
        ['iso_code' => 'SGD', 'name' => 'Singapore Dollar', 'symbol' => '$'],
        ['iso_code' => 'SHP', 'name' => 'Saint Helena Pound', 'symbol' => '£'],
        ['iso_code' => 'SLL', 'name' => 'Leone', 'symbol' => 'Le'],
        ['iso_code' => 'SOS', 'name' => 'Somali Shilling', 'symbol' => 'Sh'],
        ['iso_code' => 'SRD', 'name' => 'Surinam Dollar', 'symbol' => '$'],
        ['iso_code' => 'SSP', 'name' => 'South Sudanese Pound', 'symbol' => 'SS£'],
        ['iso_code' => 'STN', 'name' => 'Dobra', 'symbol' => 'Db'],
        ['iso_code' => 'SYP', 'name' => 'Syrian Pound', 'symbol' => '£'],
        ['iso_code' => 'SZL', 'name' => 'Lilangeni', 'symbol' => 'L'],
        ['iso_code' => 'THB', 'name' => 'Baht', 'symbol' => '฿'],
        ['iso_code' => 'TJS', 'name' => 'Somoni', 'symbol' => 'ЅМ'],
        ['iso_code' => 'TMT', 'name' => 'Turkmenistan New Manat', 'symbol' => 'm'],
        ['iso_code' => 'TND', 'name' => 'Tunisian Dinar', 'symbol' => 'د.ت'],
        ['iso_code' => 'TOP', 'name' => 'Pa\'anga', 'symbol' => 'T$'],
        ['iso_code' => 'TRY', 'name' => 'Turkish Lira', 'symbol' => 'TL'],
        ['iso_code' => 'TTD', 'name' => 'Trinidad and Tobago Dollar', 'symbol' => '$'],
        ['iso_code' => 'TWD', 'name' => 'New Taiwan Dollar', 'symbol' => 'NT$'],
        ['iso_code' => 'TZS', 'name' => 'Tanzanian Shilling', 'symbol' => 'Sh'],
        ['iso_code' => 'UAH', 'name' => 'Hryvnia', 'symbol' => '₴'],
        ['iso_code' => 'UGX', 'name' => 'Uganda Shilling', 'symbol' => 'Sh'],
        ['iso_code' => 'USD', 'name' => 'US Dollar', 'symbol' => '$'],
        ['iso_code' => 'UYU', 'name' => 'Peso Uruguayo', 'symbol' => '$'],
        ['iso_code' => 'UZS', 'name' => 'Uzbekistan Sum', 'symbol' => 'лв'],
        ['iso_code' => 'VEF', 'name' => 'Bolivar', 'symbol' => 'Bs.'],
        ['iso_code' => 'VND', 'name' => 'Dong', 'symbol' => '₫'],
        ['iso_code' => 'VUV', 'name' => 'Vatu', 'symbol' => 'Vt'],
        ['iso_code' => 'WST', 'name' => 'Tala', 'symbol' => '$'],
        ['iso_code' => 'XAF', 'name' => 'CFA Franc BEAC', 'symbol' => 'CFA Franc BEAC'],
        ['iso_code' => 'XCD', 'name' => 'East Caribbean Dollar', 'symbol' => '$'],
        ['iso_code' => 'XOF', 'name' => 'CFA Franc BCEAO', 'symbol' => 'Franc'],
        ['iso_code' => 'XPF', 'name' => 'CFP Franc', 'symbol' => '₣'],
        ['iso_code' => 'YER', 'name' => 'Yemeni Rial', 'symbol' => '﷼'],
        ['iso_code' => 'ZAR', 'name' => 'Rand', 'symbol' => 'R'],
        ['iso_code' => 'ZMW', 'name' => 'Zambian Kwacha', 'symbol' => 'ZK'],
        ['iso_code' => 'ZWL', 'name' => 'Zimbabwe Dollar', 'symbol' => '$']
    ];

    public function run(): void
    {
        foreach (self::CURRENCIES as $currency) {
            Currency::query()->create($currency);
        }
    }
}
